apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: demo-istio-install
spec:
  profile: default
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: false